// const nodemailer = require("nodemailer");
// module.exports = async ({ from, to, subject, text, html}) => {
//         let transporter = nodemailer.createTransport({
//             host: process.env.SMTP_HOST,
//             port: process.env.SMTP_PORT,
//              // true for 465, false for other ports
//             auth: {
//                 user: process.env.MAIL_USER, // generated ethereal user
//                 pass: process.env.MAIL_PASSWORD, // generated ethereal password
//             },
//         });

//         // send mail with defined transport object
//     let info = await transporter.sendMail({
//         from: `Sharify <${from}>`, // sender address
//         to: to, // list of receivers
//         subject: subject, // Subject line
//         text: text, // plain text body
//         html: html, // html body
//     });
// }

var nodemailer = require('nodemailer');
module.exports = async ({ from, to, subject, text, html}) => {
var transport = nodemailer.createTransport({
  host:process.env.SMTP_HOST ,
  port:process.env.SMTP_PORT,
  auth: {
    user: process.env.MAIL_USER, //example of generated by Mailtrap
    pass: process.env.MAIL_PASSWORD //example of generated by Mailtrap
  }
});

var mailOptions = {
  from: from,
  to:to,
  subject: subject,

  html:html
};

transport.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log('Email sent: ' + info.response);
});
}
